# Generated by Django 5.2.4 on 2025-10-10 11:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HorariosDisponiveis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('hora_inicio', models.TimeField()),
                ('hora_fim', models.TimeField()),
                ('grupos_disponiveis', models.PositiveIntegerField(default=1, help_text='Quantos grupos podem agendar neste mesmo horário.')),
            ],
            options={
                'verbose_name': 'Horário Disponível',
                'verbose_name_plural': 'Horários Disponíveis',
                'ordering': ['data', 'hora_inicio'],
            },
        ),
        migrations.CreateModel(
            name='TiposDeVisita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(help_text='Ex: Até 40 pessoas - COM EDUCADOR', max_length=100)),
                ('capacidade_maxima_pessoas', models.PositiveIntegerField()),
                ('preco_grupo_fechado', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
            ],
            options={
                'verbose_name': 'Tipo de Visita',
                'verbose_name_plural': 'Tipos de Visita',
            },
        ),
        migrations.CreateModel(
            name='Agendamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('telefone', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('Pendente', 'Pendente'), ('Notificado', 'Notificado'), ('Confirmado', 'Confirmado'), ('Cancelado', 'Cancelado')], default='Pendente', max_length=20)),
                ('quantidade_inteira', models.PositiveIntegerField(default=0, verbose_name='Visitantes (Inteira)')),
                ('quantidade_meia', models.PositiveIntegerField(default=0, verbose_name='Visitantes (Meia-Entrada)')),
                ('quantidade_gratuidade', models.PositiveIntegerField(default=0, verbose_name='Visitantes (Gratuidade)')),
                ('nome_instituicao', models.CharField(blank=True, max_length=255, null=True)),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=8)),
                ('data_agendamento', models.DateTimeField(auto_now_add=True)),
                ('horario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuario.horariosdisponiveis')),
            ],
        ),
        migrations.AddField(
            model_name='horariosdisponiveis',
            name='tipo_visita',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios', to='usuario.tiposdevisita'),
        ),
    ]
