# Generated by Django 6.0 on 2025-12-09 01:39

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArtigoPesquisa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255, verbose_name='Título do Artigo')),
                ('slug', models.SlugField(blank=True, help_text='URL amigável (deixe em branco para gerar automaticamente)', max_length=255, unique=True)),
                ('autor', models.CharField(max_length=150, verbose_name='Autor(es)')),
                ('tipo_pesquisa', models.CharField(choices=[('monografia', 'Monografia'), ('revista', 'Revista'), ('dissertacao', 'Dissertação'), ('geral', 'Geral/Outros')], default='geral', max_length=20, verbose_name='Tipo de Publicação')),
                ('link_externo_pesquisa', models.URLField(help_text='Insira o link completo (ex: https://revista.exemplo.com.br/artigo/xyz)', max_length=500, verbose_name='Link Externo da Pesquisa (URL)')),
                ('resumo_detalhado', ckeditor.fields.RichTextField(verbose_name='Resumo e Contexto (com formatação)')),
                ('data_publicacao', models.DateField(auto_now_add=True, verbose_name='Data de Cadastro')),
            ],
            options={
                'verbose_name': 'Artigo de Pesquisa',
                'verbose_name_plural': 'Artigos de Pesquisa',
                'ordering': ['-data_publicacao', 'titulo'],
            },
        ),
        migrations.CreateModel(
            name='HorariosDisponiveis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('hora_inicio', models.TimeField()),
                ('hora_fim', models.TimeField()),
                ('grupos_disponiveis', models.PositiveIntegerField(default=1, help_text='Quantos grupos podem agendar neste mesmo horário.')),
            ],
            options={
                'verbose_name': 'Horário Disponível',
                'verbose_name_plural': 'Horários Disponíveis',
                'ordering': ['data', 'hora_inicio'],
            },
        ),
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255, verbose_name='Título da Notícia')),
                ('slug', models.SlugField(blank=True, help_text='URL amigável (deixe em branco para gerar automaticamente)', max_length=255, unique=True)),
                ('capa', models.ImageField(blank=True, null=True, upload_to='noticias/capas/', verbose_name='Imagem de Capa')),
                ('conteudo', ckeditor.fields.RichTextField(verbose_name='Conteúdo Completo (Texto, Imagens, Formatação)')),
                ('data_publicacao', models.DateField(auto_now_add=True, verbose_name='Data de Criação')),
                ('status', models.CharField(choices=[('Rascunho', 'Rascunho'), ('Publicado', 'Publicado')], default='Rascunho', max_length=10)),
            ],
            options={
                'verbose_name': 'Notícia',
                'verbose_name_plural': 'Notícias',
                'ordering': ['-data_publicacao', 'titulo'],
            },
        ),
        migrations.CreateModel(
            name='TiposDeVisita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(help_text='Ex: Até 35 pessoas - COM EDUCADOR', max_length=100)),
                ('capacidade_maxima_pessoas', models.PositiveIntegerField(default=35)),
                ('preco_grupo_fechado', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
            ],
            options={
                'verbose_name': 'Tipo de Visita',
                'verbose_name_plural': 'Tipos de Visita',
            },
        ),
        migrations.CreateModel(
            name='Agendamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=255)),
                ('telefone', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('Pendente', 'Pendente'), ('Notificado', 'Notificado'), ('Confirmado', 'Confirmado'), ('Cancelado', 'Cancelado')], default='Notificado', max_length=20)),
                ('quantidade_inteira', models.PositiveIntegerField(default=0, verbose_name='Visitantes (Inteira)')),
                ('quantidade_meia', models.PositiveIntegerField(default=0, verbose_name='Visitantes (Meia-Entrada)')),
                ('quantidade_gratuidade', models.PositiveIntegerField(default=0, verbose_name='Visitantes (Gratuidade)')),
                ('nome_instituicao', models.CharField(blank=True, max_length=255, null=True)),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=8)),
                ('data_agendamento', models.DateTimeField(auto_now_add=True)),
                ('horario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.horariosdisponiveis')),
            ],
        ),
        migrations.AddField(
            model_name='horariosdisponiveis',
            name='tipo_visita',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios', to='base.tiposdevisita'),
        ),
    ]
