# Generated by Django 6.0 on 2025-12-09 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='artigopesquisa',
            name='ano_publicacao_artigo',
            field=models.IntegerField(blank=True, help_text='O ano em que o artigo foi efetivamente publicado.', null=True, verbose_name='Ano de Publicação Original (Ex: 2023)'),
        ),
        migrations.AlterField(
            model_name='artigopesquisa',
            name='titulo',
            field=models.CharField(max_length=120, verbose_name='Título do Artigo'),
        ),
    ]
