# Generated by Django 6.0 on 2025-12-09 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_artigopesquisa_ano_publicacao_artigo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artigopesquisa',
            name='titulo',
            field=models.CharField(max_length=150, verbose_name='Título do Artigo'),
        ),
    ]
