# Generated by Django 6.0 on 2025-12-09 22:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_artigopesquisa_titulo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='noticia',
            options={'ordering': ['-data_publicacao'], 'verbose_name': 'Notícia', 'verbose_name_plural': 'Notícias'},
        ),
        migrations.AddField(
            model_name='noticia',
            name='chamada',
            field=models.TextField(blank=True, help_text='Texto curto (máx. 300 caracteres) que resume a notícia e atrai o leitor. Aparece logo abaixo do título principal.', max_length=300, null=True, verbose_name='Chamada/Subtítulo (Impacto)'),
        ),
        migrations.AddField(
            model_name='noticia',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='noticias_criadas', to=settings.AUTH_USER_MODEL, verbose_name='Criado Por'),
        ),
        migrations.AddField(
            model_name='noticia',
            name='data_modificacao',
            field=models.DateTimeField(auto_now=True, verbose_name='Última Modificação'),
        ),
        migrations.AddField(
            model_name='noticia',
            name='fonte_capa',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Fonte/Crédito da Imagem de Capa'),
        ),
        migrations.AddField(
            model_name='noticia',
            name='legenda_capa',
            field=models.CharField(blank=True, help_text='Descrição curta da imagem (importante para SEO e acessibilidade).', max_length=255, null=True, verbose_name='Legenda da Imagem de Capa (Alt Text)'),
        ),
        migrations.AddField(
            model_name='noticia',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='noticias_modificadas', to=settings.AUTH_USER_MODEL, verbose_name='Modificado Por'),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='data_publicacao',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação'),
        ),
    ]
